#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_ShieldFlash

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_ShieldFlash.BPI_ShieldFlash_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_ShieldFlash_C final
{
public:
	void FlashShield();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_ShieldFlash_C">();
	}
	static class IBPI_ShieldFlash_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_ShieldFlash_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_ShieldFlash_C) == 0x000001, "Wrong alignment on IBPI_ShieldFlash_C");
static_assert(sizeof(IBPI_ShieldFlash_C) == 0x000001, "Wrong size on IBPI_ShieldFlash_C");

}

