#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DeimosTypeInfo

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DeimosTypeInfo.DeimosTypeInfo_C
// 0x0000 (0x0000 - 0x0000)
class IDeimosTypeInfo_C final
{
public:
	void GetEnemyColor(struct FLinearColor* Color) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DeimosTypeInfo_C">();
	}
	static class IDeimosTypeInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IDeimosTypeInfo_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IDeimosTypeInfo_C) == 0x000001, "Wrong alignment on IDeimosTypeInfo_C");
static_assert(sizeof(IDeimosTypeInfo_C) == 0x000001, "Wrong size on IDeimosTypeInfo_C");

}

