#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortAnimNotify_Interface_Interface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FortAnimNotify_Interface_Interface.FortAnimNotify_Interface_Interface_C
// 0x0000 (0x0000 - 0x0000)
class IFortAnimNotify_Interface_Interface_C final
{
public:
	void TrailOff();
	void TrailOn();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FortAnimNotify_Interface_Interface_C">();
	}
	static class IFortAnimNotify_Interface_Interface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IFortAnimNotify_Interface_Interface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IFortAnimNotify_Interface_Interface_C) == 0x000001, "Wrong alignment on IFortAnimNotify_Interface_Interface_C");
static_assert(sizeof(IFortAnimNotify_Interface_Interface_C) == 0x000001, "Wrong size on IFortAnimNotify_Interface_Interface_C");

}

