#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IceQueen_Glider_AnimBP

#include "Basic.hpp"

#include "IceQueen_Glider_AnimBP_classes.hpp"
#include "IceQueen_Glider_AnimBP_parameters.hpp"


namespace SDK
{

// Function IceQueen_Glider_AnimBP.IceQueen_Glider_AnimBP_C.ExecuteUbergraph_IceQueen_Glider_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UIceQueen_Glider_AnimBP_C::ExecuteUbergraph_IceQueen_Glider_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IceQueen_Glider_AnimBP_C", "ExecuteUbergraph_IceQueen_Glider_AnimBP");

	Params::IceQueen_Glider_AnimBP_C_ExecuteUbergraph_IceQueen_Glider_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function IceQueen_Glider_AnimBP.IceQueen_Glider_AnimBP_C.AnimNotify_FE_IdleStart
// (BlueprintCallable, BlueprintEvent)

void UIceQueen_Glider_AnimBP_C::AnimNotify_FE_IdleStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IceQueen_Glider_AnimBP_C", "AnimNotify_FE_IdleStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IceQueen_Glider_AnimBP.IceQueen_Glider_AnimBP_C.AnimNotify_TurnONEngines
// (BlueprintCallable, BlueprintEvent)

void UIceQueen_Glider_AnimBP_C::AnimNotify_TurnONEngines()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IceQueen_Glider_AnimBP_C", "AnimNotify_TurnONEngines");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IceQueen_Glider_AnimBP.IceQueen_Glider_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceQueen_Glider_AnimBP_AnimGraphNode_BlendListByBool_2FF6C0244671D0A94B127EB3A3E9F2D0
// (BlueprintEvent)

void UIceQueen_Glider_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_IceQueen_Glider_AnimBP_AnimGraphNode_BlendListByBool_2FF6C0244671D0A94B127EB3A3E9F2D0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IceQueen_Glider_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_IceQueen_Glider_AnimBP_AnimGraphNode_BlendListByBool_2FF6C0244671D0A94B127EB3A3E9F2D0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IceQueen_Glider_AnimBP.IceQueen_Glider_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceQueen_Glider_AnimBP_AnimGraphNode_BlendListByBool_A44C17B747C5420618D113B928FD4215
// (BlueprintEvent)

void UIceQueen_Glider_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_IceQueen_Glider_AnimBP_AnimGraphNode_BlendListByBool_A44C17B747C5420618D113B928FD4215()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IceQueen_Glider_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_IceQueen_Glider_AnimBP_AnimGraphNode_BlendListByBool_A44C17B747C5420618D113B928FD4215");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IceQueen_Glider_AnimBP.IceQueen_Glider_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceQueen_Glider_AnimBP_AnimGraphNode_BlendListByBool_B161E5AA45ECFAE2909BA98ADD6FB3A5
// (BlueprintEvent)

void UIceQueen_Glider_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_IceQueen_Glider_AnimBP_AnimGraphNode_BlendListByBool_B161E5AA45ECFAE2909BA98ADD6FB3A5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IceQueen_Glider_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_IceQueen_Glider_AnimBP_AnimGraphNode_BlendListByBool_B161E5AA45ECFAE2909BA98ADD6FB3A5");

	UObject::ProcessEvent(Func, nullptr);
}

}

