#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IceQueen_Glider_AnimBP

#include "Basic.hpp"


namespace SDK::Params
{

// Function IceQueen_Glider_AnimBP.IceQueen_Glider_AnimBP_C.ExecuteUbergraph_IceQueen_Glider_AnimBP
// 0x0004 (0x0004 - 0x0000)
struct IceQueen_Glider_AnimBP_C_ExecuteUbergraph_IceQueen_Glider_AnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(IceQueen_Glider_AnimBP_C_ExecuteUbergraph_IceQueen_Glider_AnimBP) == 0x000004, "Wrong alignment on IceQueen_Glider_AnimBP_C_ExecuteUbergraph_IceQueen_Glider_AnimBP");
static_assert(sizeof(IceQueen_Glider_AnimBP_C_ExecuteUbergraph_IceQueen_Glider_AnimBP) == 0x000004, "Wrong size on IceQueen_Glider_AnimBP_C_ExecuteUbergraph_IceQueen_Glider_AnimBP");
static_assert(offsetof(IceQueen_Glider_AnimBP_C_ExecuteUbergraph_IceQueen_Glider_AnimBP, EntryPoint) == 0x000000, "Member 'IceQueen_Glider_AnimBP_C_ExecuteUbergraph_IceQueen_Glider_AnimBP::EntryPoint' has a wrong offset!");

}

